# Generated by Django 4.2.4 on 2023-09-12 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profileimp',
            new_name='profileimg',
        ),
    ]
